global:
  message:welcome to global microservices environment
logging:
  level:
    root:Info
management:
  endpoints:
    web:
      exposure:
        include:health,info,refresh
  endpoint:
    health:
      show_details:always
