global:
  message: welcome to Customer service Dev environment
server:
  port: 8085
message: hello from dec!
spring:
  datasource:      
   datasource:
    url: jdbc:mysql://localhost:3306/order_prod
    username: root
    password: komal
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
